GET http://localhost:3000/posts
Authorization: Bearer **accessToken**
###

GET http://localhost:4000/token
Content-Type: application/json

{
    "token": "**refreshToken**"
}
###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "**refreshToken**"
}


###

GET http://localhost:4000/users


###

POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "Yehuda",
    "password": "Passsword"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "name": "Yehuda",
    "password": "Passsword"
}
